[pytest]
testpaths = tests

markers =
    slow: marks tests as slow-running (deselect with '-m "not slow"')
    confusability: marks tests as part of the confusability test suite (run with '-m confusability')
